# See wiki for current client_id and secret values.
#   http://wiki.htrc.illinois.edu/display/DEV/HTRC-UI-Blacklight


development:
   add_google_analytics?: false
   google_analytics_tracking_code: 'none'
   do_pairtree_substitutions?: false
   register_url: 'http://htrc5.pti.indiana.edu:9443/HTRC-UI-Portal2/SignUpAction'
   solr_proxy_meta_url: 'http://chinkapin.pti.indiana.edu:9446/solr/meta'
   registry_url: 'https://htrc4.pti.indiana.edu:9443/ExtensionAPI-1.0.4-SNAPSHOT/services'
   site_url: 'https://htrc3.pti.indiana.edu:9443/oauth2/authorize'
   authorize_url: 'https://htrc3.pti.indiana.edu:9443/oauth2/authorize'
   access_token_url: 'https://htrc3.pti.indiana.edu:9443/oauth2endpoints/token'
   token_url: 'https://htrc3.pti.indiana.edu:9443/oauth2endpoints/token'
   userinfo_url: 'https://htrc3.pti.indiana.edu:9443/oauth2userinfo/userinfo'
   portal_url: 'http://htrc5.pti.indiana.edu:9443/HTRC-UI-Portal2'
   callback_url: 'http://htrc6.pti.indiana.edu:9443/users/auth/wso2/callback'
   oauth2_client_id: 'DEVELOPMENT_CLIENT_ID'
   oauth2_secret: 'DEVELOPMENT_SECRET'

sandbox:
   add_google_analytics?: true
   google_analytics_tracking_code: 'UA-42842720-4'
   do_pairtree_substitutions?: true
   register_url: 'https://sandbox.htrc.illinois.edu:8443/HTRC-UI-Portal2/SignUpAction'
   solr_proxy_meta_url: 'http://sandbox.htrc.illinois.edu:9994/solr/meta'
   registry_url: 'https://sandbox.htrc.illinois.edu:9444/ExtensionAPI-1.0.0/services'
   site_url:  'https://sandbox.htrc.illinois.edu:9443/oauth2/authorize'
   authorize_url: 'https://sandbox.htrc.illinois.edu:9443/oauth2/authorize'
   access_token_url: 'https://sandbox.htrc.illinois.edu9443/oauth2endpoints/token'
   token_url: 'https://sandbox.htrc.illinois.edu:9443/oauth2endpoints/token'
   userinfo_url: 'https://sandbox.htrc.illinois.edu:9443/oauth2userinfo/userinfo'
   portal_url: 'https://sandbox.htrc.illinois.edu:8443/HTRC-UI-Portal2/'
   callback_url: 'https://sandbox.htrc.illinois.edu:8443/users/auth/wso2/callback'
   oauth2_client_id: 'SANDBOX_CLIENT_ID'
   oauth2_secret: 'SANDBOX_SECRET'

production:
   add_google_analytics?: true
   google_analytics_tracking_code: 'UA-42842720-2'
   do_pairtree_substitutions?: false
   register_url: 'https://htrc2.pti.indiana.edu/HTRC-UI-Portal2/SignUpAction'
   solr_proxy_meta_url: 'http://chinkapin.pti.indiana.edu:9446/solr/meta'
   registry_url: 'https://chinkapin.pti.indiana.edu:9443/ExtensionAPI-1.0.0/services'
   site_url:  'https://silvermaple.pti.indiana.edu:9443/oauth2/authorize'
   authorize_url: 'https://silvermaple.pti.indiana.edu:9443/oauth2/authorize'
   access_token_url: 'https://silvermaple.pti.indiana.edu:9443/oauth2endpoints/token'
   token_url: 'https://silvermaple.pti.indiana.edu:9443/oauth2endpoints/token'
   userinfo_url: 'https://silvermaple.pti.indiana.edu:9443/oauth2userinfo/userinfo'
   portal_url: 'https://htrc2.pti.indiana.edu/HTRC-UI-Portal2/'
   callback_url: 'http://htrc6.pti.indiana.edu:9443/users/auth/wso2/callback'
   oauth2_client_id: 'PRODUCTION_CLIENT_ID'
   oauth2_secret: 'PRODUCTION_SECRET'
