# See wiki for current client_id and secret values.
#   http://wiki.htrc.illinois.edu/display/DEV/HTRC-UI-Blacklight

development:
   add_google_analytics?:          true
   google_analytics_tracking_code: <GA_TRACKING_CODE>
   devise_key:                     <DEVISE_KEY>
   register_url:                   'https://chinkapin.pti.indiana.edu/signup'
   solr_proxy_meta_url:            'http://chinkapin.pti.indiana.edu:9994/solr/meta'
   registry_url:                   'https://htrc3.pti.indiana.edu:9443/ExtensionAPI/services'
   site_url:                       'https://htrc3.pti.indiana.edu:9443/oauth2/authorize'
   authorize_url:                  'https://htrc3.pti.indiana.edu:9443/oauth2/authorize'
   access_token_url:               'https://htrc3.pti.indiana.edu:9443/oauth2/token'
   token_url:                      'https://htrc3.pti.indiana.edu:9443/oauth2/token'   
   userinfo_url:                   'https://htrc3.pti.indiana.edu:9443/oauth2/userinfo'
   portal_url:                     'https://chinkapin.pti.indiana.edu'
   callback_url:                   'https://htrc6.pti.indiana.edu:9443/users/auth/wso2/callback'
   oauth2_client_id:               <OAUTH2_CLIENT_ID>
   oauth2_secret:                  <OAUTH2_SECRET>

